-- Course codes are generated by the application from this database sequence.
-- Example: LR-2607-001 or SW-2607-002.
create sequence if not exists public.course_code_seq start with 1 increment by 1;

comment on sequence public.course_code_seq is
  'Global sequence used to generate human-readable, immutable course codes.';
